"""
main.py — BLIP-2 VQA Backend
Run this ONCE to load the model, then keep it alive while Streamlit is running.
The Streamlit app imports get_model() from here via st.session_state caching.
"""
# import warnings
# warnings.filterwarnings("ignore")
# from transformers import logging
# logging.set_verbosity_error()

import torch
from PIL import Image
from transformers import AutoProcessor, Blip2ForConditionalGeneration


# --------------------------------------------------------------------------- #
#  Model loading (cached — only runs once per Python process)                 #
# --------------------------------------------------------------------------- #

_processor = None
_model = None


def get_model():
    """Return (processor, model). Loads from HuggingFace on first call only."""
    global _processor, _model

    if _processor is None or _model is None:
        print("[INFO] Loading BLIP-2 processor …")
        _processor = AutoProcessor.from_pretrained("Salesforce/blip2-opt-2.7b")

        print("[INFO] Loading BLIP-2 model (this may take a few minutes) …")
        _model = Blip2ForConditionalGeneration.from_pretrained(
            "Salesforce/blip2-opt-2.7b",
            torch_dtype=torch.float16,
            device_map="auto",
        )
        _model.eval()
        print("[INFO] Model ready.")

    return _processor, _model


# --------------------------------------------------------------------------- #
#  Inference                                                                  #
# --------------------------------------------------------------------------- #

def answer_question(image: Image.Image, question: str) -> str:
    """
    Run BLIP-2 VQA on a PIL image and a text question.

    Args:
        image:    RGB PIL image.
        question: Natural-language question string.

    Returns:
        Answer string generated by the model.
    """
    if image is None or not question.strip():
        return "Please provide both an image and a question."

    processor, model = get_model()

    # Prepare inputs
    inputs = processor(images=image, text=question, return_tensors="pt")
    inputs = inputs.to("cuda")

    # Generate answer
    with torch.no_grad():
        generated_ids = model.generate(
            **inputs,
            max_new_tokens=64,
            num_beams=4,
            early_stopping=True,
        )

    # Decode — skip the prompt tokens that were echoed back
    generated_text = processor.batch_decode(
        generated_ids, skip_special_tokens=True
    )[0].strip()

    return generated_text


# --------------------------------------------------------------------------- #
#  Quick smoke-test (python main.py)                                          #
# --------------------------------------------------------------------------- #

if __name__ == "__main__":
    import sys

    img_path = sys.argv[1] if len(sys.argv) > 1 else None
    question  = sys.argv[2] if len(sys.argv) > 2 else "What is in this image?"

    if img_path is None:
        print("Usage: python main.py <image_path> [question]")
        sys.exit(1)

    image = Image.open(img_path).convert("RGB")
    print(f"Question : {question}")
    print(f"Answer   : {answer_question(image, question)}")
